apiVersion: v1
kind: Service
metadata:
  name: smart-price-predictor-service
spec:
  type: NodePort   # or LoadBalancer if using a cloud cluster
  selector:
    app: smart-price-predictor
  ports:
    - protocol: TCP
      port: 8000         # service port
      targetPort: 8000   # inside the container
      nodePort: 30080    # accessible on http://localhost:30080
